name: Elm Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Elm
      uses: jorelali/setup-elm@v1
      with:
        elm-version: 0.19.1
    - run: npm install -g elm-test
    - run: elm-test
